# Generated by Django 4.2.11 on 2024-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('id_Gps', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(default=0, max_length=13)),
                ('longitude', models.CharField(default=0, max_length=13)),
            ],
        ),
    ]
